# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: paul.a94361@gmail.com
author_name: John Doe
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: Albatrosses

